In [80]:
import numpy as np
from sklearn import preprocessing

In [82]:
set_size = 128
sample_size = 4

x_train = np.random.randint(2, size=(set_size, sample_size))
y_train = np.logical_and(x_train[:, 0:1], x_train[:, 1:2])

print(x_train[:8])
print(y_train[:8])

[[0 1 1 1]
 [0 0 1 0]
 [1 1 0 0]
 [0 1 0 1]
 [1 1 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 0 1 1]]
[[False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]]


In [83]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

def mse1(y, truth):
    return (y - truth)**2

def dmse1(y, truth):
    return 2*(y - truth)


class Model():
    def __init__(self, input_size):
        self.input_size = input_size
        self.W = np.random.randn(1, input_size)
        self.b = np.random.randn(1, 1)

    def __repr__(self):
        return '{} {}'.format(
            str(np.around(self.W, decimals = 5)),
            str(np.around(self.b, decimals = 5))
        )

    def predict(self, x):
        return sigmoid(np.dot(self.W, x) + self.b)

    def fit(self, x_input, y_input, epochs=10, lr=1):
        for e in range(epochs):
            loss = []
            for i in range(x_input.shape[0]):
                inp = x_input[i].reshape(self.input_size, 1)
                prediction = self.predict(inp)
            
                cost = mse1(prediction, y_input[i])
                loss.append(cost)
            
                dcost = dmse1(prediction, y_input[i])
                dprediction = dsigmoid(prediction)
                dW = inp.T
                self.W -= lr * dW * dprediction * dcost
                self.b -= lr * dprediction * dcost
            print('{}/{} Loss: {:.5f}'.format(e + 1, epochs, np.average(loss)))


model = Model(input_size = sample_size)
model

[[-0.54626  0.05914 -2.50467 -0.50812]] [[0.55621]]

In [84]:
model.fit(x_train, y_train, epochs=10)

1/10 Loss: 0.15009
2/10 Loss: 0.03851
3/10 Loss: 0.01700
4/10 Loss: 0.00945
5/10 Loss: 0.00598
6/10 Loss: 0.00411
7/10 Loss: 0.00300
8/10 Loss: 0.00228
9/10 Loss: 0.00179
10/10 Loss: 0.00145


In [85]:
x_test = np.random.randint(2, size=(10, sample_size))
for x in x_test:
    prediction = model.predict(np.array([x]).T)[0, 0]
    print('{} {:.5f} {:.5f}'.format(x, prediction, mse1(prediction, x[0])))

[0 1 0 1] 0.02320 0.00054
[0 1 1 0] 0.04480 0.00201
[1 0 0 1] 0.01996 0.96048
[1 1 0 0] 0.95850 0.00172
[1 1 1 0] 0.95974 0.00162
[1 1 0 0] 0.95850 0.00172
[1 0 1 0] 0.03866 0.92417
[0 0 0 1] 0.00004 0.00000
[1 0 1 1] 0.02059 0.95925
[0 0 1 0] 0.00008 0.00000


In [86]:
model

[[ 6.23093  6.3847   0.03155 -0.64892]] [[-9.47594]]