In [1]:
import numpy as np

In [2]:
set_size = 128
sample_size = 4

x_train = np.random.randint(2, size=(set_size, sample_size))
y_train = x_train[:, :1]

print(x_train[:5])
print(y_train[:5])

[[1 1 1 0]
 [1 0 0 0]
 [0 0 1 1]
 [1 1 0 1]
 [1 0 0 1]]
[[1]
 [1]
 [0]
 [1]
 [1]]


In [3]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

def mse1(y, truth):
    return (y - truth)**2

def dmse1(y, truth):
    return 2*(y - truth)


class Model():
    def __init__(self, input_size):
        self.input_size = input_size
        self.W = np.random.randn(1, input_size)
        self.b = np.random.randn(1, 1)

    def __repr__(self):
        return '{} {}'.format(
            str(np.around(self.W, decimals = 5)),
            str(np.around(self.b, decimals = 5))
        )

    def predict(self, x):
        return sigmoid(np.dot(self.W, x) + self.b)

    def fit(self, x_input, y_input, epochs=10, lr=1):
        for e in range(epochs):
            loss = []
            for i in range(x_input.shape[0]):
                inp = x_input[i].reshape(self.input_size, 1)
                prediction = self.predict(inp)
            
                cost = mse1(prediction, y_input[i])
                loss.append(cost)
            
                dcost = dmse1(prediction, y_input[i])
                dprediction = dsigmoid(prediction)
                dW = inp.T
                self.W -= lr * dW * dprediction * dcost
                self.b -= lr * dprediction * dcost
            print('{}/{} Loss: {:.5f}'.format(e + 1, epochs, np.average(loss)))


model = Model(input_size = sample_size)
model

[[-0.33607  1.10066  0.76713 -0.64875]] [[0.31805]]

In [4]:
model.fit(x_train, y_train, epochs=5)

1/5 Loss: 0.07490
2/5 Loss: 0.00454
3/5 Loss: 0.00149
4/5 Loss: 0.00074
5/5 Loss: 0.00044


In [5]:
x_test = np.random.randint(2, size=(10, sample_size))
for x in x_test:
    prediction = model.predict(np.array([x]).T)[0, 0]
    print('{} {:.5f} {:.5f}'.format(x, prediction, mse1(prediction, x[0])))

[1 0 1 1] 0.98684 0.00017
[1 1 0 0] 0.98864 0.00013
[1 1 0 0] 0.98864 0.00013
[0 0 1 1] 0.02095 0.00044
[1 0 1 1] 0.98684 0.00017
[0 0 1 0] 0.03001 0.00090
[0 1 1 1] 0.01555 0.00024
[0 1 1 0] 0.02234 0.00050
[0 1 0 0] 0.02424 0.00059
[0 0 1 0] 0.03001 0.00090


In [6]:
model

[[ 8.16177 -0.30327 -0.08364 -0.36897]] [[-3.39196]]