In [40]:
import numpy as np
from sklearn import preprocessing

In [63]:
set_size = 10240
sample_size = 4

range_x = (2, 20)
x_train = np.random.randint(range_x[0], range_x[1], size=(set_size, sample_size))
x_train = preprocessing.normalize(x_train)
y_train = x_train[:, :1]

print(x_train[:8])
print(y_train[:8])

[[0.07974522 0.63796178 0.59808917 0.47847133]
 [0.17457431 0.61101009 0.52372294 0.56736651]
 [0.6144763  0.19202384 0.7296906  0.23042861]
 [0.61186276 0.2447451  0.57107191 0.48949021]
 [0.61288338 0.20429446 0.20429446 0.73546006]
 [0.39181389 0.39181389 0.62037199 0.55506968]
 [0.08830216 0.57396402 0.52981294 0.6181151 ]
 [0.11009638 0.16514456 0.60553007 0.77067464]]
[[0.07974522]
 [0.17457431]
 [0.6144763 ]
 [0.61186276]
 [0.61288338]
 [0.39181389]
 [0.08830216]
 [0.11009638]]


In [64]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

def mse1(y, truth):
    return (y - truth)**2

def dmse1(y, truth):
    return 2*(y - truth)


class Model():
    def __init__(self, input_size):
        self.input_size = input_size
        self.W = np.random.randn(1, input_size)
        self.b = np.random.randn(1, 1)

    def __repr__(self):
        return '{} {}'.format(
            str(np.around(self.W, decimals = 5)),
            str(np.around(self.b, decimals = 5))
        )

    def predict(self, x):
        return sigmoid(np.dot(self.W, x) + self.b)

    def fit(self, x_input, y_input, epochs=10, lr=1):
        for e in range(epochs):
            loss = []
            for i in range(x_input.shape[0]):
                inp = x_input[i].reshape(self.input_size, 1)
                prediction = self.predict(inp)
            
                cost = mse1(prediction, y_input[i])
                loss.append(cost)
            
                dcost = dmse1(prediction, y_input[i])
                dprediction = dsigmoid(prediction)
                dW = inp.T
                self.W -= lr * dW * dprediction * dcost
                self.b -= lr * dprediction * dcost
            print('{}/{} Loss: {:.5f}'.format(e + 1, epochs, np.average(loss)))


model = Model(input_size = sample_size)
model

[[ 1.29873  0.62113  0.07035 -0.45316]] [[0.45118]]

In [65]:
model.fit(x_train, y_train, epochs=10)

1/10 Loss: 0.00070
2/10 Loss: 0.00027
3/10 Loss: 0.00026
4/10 Loss: 0.00026
5/10 Loss: 0.00026
6/10 Loss: 0.00026
7/10 Loss: 0.00026
8/10 Loss: 0.00026
9/10 Loss: 0.00026
10/10 Loss: 0.00026


In [66]:
x_test = np.random.randint(range_x[0], range_x[1], size=(20, sample_size))
x_test = preprocessing.normalize(x_test)
for x in x_test:
    prediction = model.predict(np.array([x]).T)[0, 0]
    print('{} {:.5f} {:.5f}'.format(x, prediction, mse1(prediction, x[0])))

[0.51261459 0.34174306 0.76892189 0.17087153] 0.50833 0.00002
[0.29528539 0.5536601  0.66439212 0.40601741] 0.27896 0.00027
[0.54772256 0.79115481 0.12171612 0.24343225] 0.54857 0.00000
[0.65870958 0.12350805 0.61754023 0.41169348] 0.66996 0.00013
[0.22423053 0.67269158 0.59794807 0.37371755] 0.21763 0.00004
[0.58309519 0.48019604 0.44589632 0.48019604] 0.59395 0.00012
[0.72101012 0.36050506 0.54075759 0.24033671] 0.73086 0.00010
[0.36147845 0.72295689 0.56803756 0.15491933] 0.34162 0.00039
[0.32816506 0.79697229 0.42192651 0.28128434] 0.30906 0.00037
[0.36835473 0.44202568 0.47886115 0.66303852] 0.35252 0.00025
[0.25979437 0.63092918 0.29690785 0.66804266] 0.24740 0.00015
[0.3796283  0.3796283  0.59655876 0.59655876] 0.36400 0.00024
[0.53381684 0.41519088 0.56347333 0.47450386] 0.53804 0.00002
[0.83550442 0.24573659 0.29488391 0.39317855] 0.82043 0.00023
[0.33218192 0.33218192 0.66436384 0.58131836] 0.31418 0.00032
[0.44694921 0.55009133 0.48132991 0.51571062] 0.43928 0.00006
[0.43895

In [58]:
model

[[0.12235 4.69458 0.08546 0.0818 ]] [[-2.4998]]