In [1]:
import numpy as np

In [126]:
size = 128

x_train = np.random.randint(2, size=(size, 4))
#y_train = np.logical_or(x_train[:, :1], x_train[:, 3:4])
y_train = np.logical_not(x_train[:, :1])

print(x_train[:5])
print(y_train[:5])

[[1 0 1 1]
 [0 0 1 1]
 [0 1 1 1]
 [1 1 0 0]
 [0 0 1 1]]
[[False]
 [ True]
 [ True]
 [False]
 [ True]]


In [127]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

def mse1(y, truth):
    return (y - truth)**2

def dmse1(y, truth):
    return 2*(y - truth)


class Model():
    def __init__(self):
        self.W = np.random.randn(1, 4) * 0.1
        self.b = np.random.randn(1, 1) * 0.1

    def __repr__(self):
        return '{} {}'.format(
            str(np.around(self.W, decimals = 5)),
            str(np.around(self.b, decimals = 5))
        )

    def predict(self, x):
        return sigmoid(np.dot(self.W, x) + self.b)

    def fit(self, x_input, y_input, epochs=10, lr=1):
        for e in range(epochs):
            loss = []
            for i in range(x_input.shape[0]):
                inp = x_input[i].T
                prediction = self.predict(inp)
            
                cost = mse1(prediction, y_input[i])
                loss.append(cost)
            
                dcost = dmse1(prediction, y_input[i])
                dprediction = dsigmoid(prediction)
                dW = inp
                self.W -= lr * dW * dprediction * dcost
                self.b -= lr * dprediction * dcost
            print('{}/{} Loss: {:.3f}'.format(e + 1, epochs, np.average(loss)))


model = Model()
model

[[-0.09321 -0.0065  -0.17248  0.09445]] [[-0.03121]]

In [128]:
model.fit(x_train, y_train, epochs=5)

1/5 Loss: 0.057
2/5 Loss: 0.005
3/5 Loss: 0.002
4/5 Loss: 0.001
5/5 Loss: 0.001


In [129]:
x_test = np.random.randint(2, size=(10, 4))
for x in x_test:
    prediction = model.predict(np.array([x]).T)[0, 0]
    print('{} {:.5f} {:.5f}'.format(x, prediction, mse1(prediction, x[0])))

[0 0 1 0] 0.97772 0.95594
[0 1 1 0] 0.97751 0.95552
[0 1 0 0] 0.96145 0.92439
[0 1 1 0] 0.97751 0.95552
[0 0 1 0] 0.97772 0.95594
[1 1 0 1] 0.01523 0.96977
[1 0 0 1] 0.01538 0.96948
[0 0 0 0] 0.96181 0.92508
[1 1 0 1] 0.01523 0.96977
[1 0 0 0] 0.00727 0.98550


In [130]:
model

[[-8.1424  -0.00983  0.55528  0.75684]] [[3.22633]]