In [40]:
import numpy as np
from sklearn import preprocessing

In [76]:
set_size = 128
sample_size = 4

x_train = np.random.randint(2, size=(set_size, sample_size))
y_train = np.logical_xor(x_train[:, 0:1], x_train[:, 1:2])

print(x_train[:8])
print(y_train[:8])

[[0 0 0 0]
 [0 0 0 1]
 [0 1 1 1]
 [1 1 1 1]
 [0 0 1 0]
 [0 1 0 1]
 [0 0 0 1]
 [0 1 0 1]]
[[False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]]


In [77]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return sigmoid(x)*(1 - sigmoid(x))

def mse1(y, truth):
    return (y - truth)**2

def dmse1(y, truth):
    return 2*(y - truth)


class Model():
    def __init__(self, input_size):
        self.input_size = input_size
        self.W = np.random.randn(1, input_size)
        self.b = np.random.randn(1, 1)

    def __repr__(self):
        return '{} {}'.format(
            str(np.around(self.W, decimals = 5)),
            str(np.around(self.b, decimals = 5))
        )

    def predict(self, x):
        return sigmoid(np.dot(self.W, x) + self.b)

    def fit(self, x_input, y_input, epochs=10, lr=1):
        for e in range(epochs):
            loss = []
            for i in range(x_input.shape[0]):
                inp = x_input[i].reshape(self.input_size, 1)
                prediction = self.predict(inp)
            
                cost = mse1(prediction, y_input[i])
                loss.append(cost)
            
                dcost = dmse1(prediction, y_input[i])
                dprediction = dsigmoid(prediction)
                dW = inp.T
                self.W -= lr * dW * dprediction * dcost
                self.b -= lr * dprediction * dcost
            print('{}/{} Loss: {:.5f}'.format(e + 1, epochs, np.average(loss)))


model = Model(input_size = sample_size)
model

[[ 0.95718  0.49538 -0.56633 -0.23754]] [[-0.23787]]

In [78]:
model.fit(x_train, y_train, epochs=10)

1/10 Loss: 0.30031
2/10 Loss: 0.29804
3/10 Loss: 0.29821
4/10 Loss: 0.29823
5/10 Loss: 0.29823
6/10 Loss: 0.29823
7/10 Loss: 0.29823
8/10 Loss: 0.29823
9/10 Loss: 0.29823
10/10 Loss: 0.29823


In [79]:
x_test = np.random.randint(2, size=(10, sample_size))
for x in x_test:
    prediction = model.predict(np.array([x]).T)[0, 0]
    print('{} {:.5f} {:.5f}'.format(x, prediction, mse1(prediction, x[0])))

[0 0 0 0] 0.25518 0.06512
[0 0 0 0] 0.25518 0.06512
[0 0 1 0] 0.24313 0.05911
[1 0 0 0] 0.11648 0.78061
[0 1 1 0] 0.25796 0.06654
[1 0 0 0] 0.11648 0.78061
[1 0 1 0] 0.11001 0.79208
[0 1 0 0] 0.27049 0.07316
[0 1 1 1] 0.23390 0.05471
[1 0 1 0] 0.11001 0.79208


In [75]:
model

[[ 7.49682  7.41103 -0.43869 -0.1212 ]] [[-2.80687]]